version: '2'
services:
  library-apache:
    #image: mozgbrasil/docker-php
    build: .
    ports:
      - "80:80"
    volumes:
      # Mount volumes related to ln -s htdocs
      - /home/marcio/dados/:/home/marcio/dados/
      # Mount custom mass virtual hosting
      - ~/dados/mount/www/:/var/www/html/
      # Mount user-defined *.ini files in order to overwrite the default *.ini configuration
      #- ./php-conf:/usr/local/etc/php/conf.d:ro
      # Mount user-defined *.conf files in order to overwrite the default *.conf configuration
      #- ./apache-conf:/etc/apache2/sites-available:ro
      # Mount user-defined *.so files in order to load custom PHP modules
      - ./modules/:/usr/lib64/php/custom-modules/

#  library-mariadb:
#    image: mariadb
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '3307:3306'
#    volumes:
#      # Mount MySQL Data directory
#      - ~/dados/mount/mariadb-data3/:/var/lib/mysql/
#  library-phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - library-mariadb
#    environment:
#      #- MYSQL_ROOT_PASSWORD=root
#      - PMA_ARBITRARY=1
#      - PMA_HOST=library-mariadb
#      #- PMA_VERBOSE=library-mariadb
#      - PMA_PORT=3307
#      #- PMA_HOSTS=???
#      #- PMA_USER=root
#      #- PMA_PASSWORD=root
#      #- PMA_ABSOLUTE_URI=???
#    ports:
#      - 8087:80
#    volumes:
#      # Mount MySQL Data directory
#      - ~/dados/mount/mariadb-data3/:/var/lib/mysql/

  bitnami-fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    depends_on:
      - library-apache
    user: root
    command: chown -R 1001:1001 /bitnami/mariadb/data/
    volumes:
      - ~/dados/mount/mariadb-data/:/bitnami/mariadb/data/
  bitnami-mariadb:
    image: 'bitnami/mariadb:latest'
    depends_on:
      - bitnami-fix-mariadb-permissions
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - ~/dados/mount/mariadb-data/:/bitnami/mariadb/data/
  bitnami-phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - bitnami-mariadb
    environment:
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
      - PHPMYADMIN_ALLOW_NO_PASSWORD=yes
      - DATABASE_HOST=bitnami-mariadb
      - DATABASE_PORT_NUMBER=3306
      #- WEBSERVER_REQUIRE=all granted
    ports:
      - '8080:80'
    volumes:
      - ~/dados/mount/mariadb-data/:/bitnami/mariadb/data/